### Работа с numpy

In [2]:
import numpy as np

In [3]:
np.fromfunction(lambda x, y: (x + y)%2, (5, 5), dtype=np.int32)

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]], dtype=int32)

In [45]:
v1 = np.array([0, 0, 5])
v2 = np.array([1, 1, 1])

skal = np.dot(v1, v2)
vect = np.cross(v1, v2)

cos = skal / (np.linalg.norm(v1) * np.linalg.norm(v2))
sin = np.linalg.norm(vect) / (np.linalg.norm(v1) * np.linalg.norm(v2))

print("Через скалярное произведение: {:.1f}".format(np.degrees(np.arccos(cos))))
print("Через векторное произведение: {:.1f}".format(np.degrees(np.arcsin(sin))))

Через скалярное произведение: 54.7
Через векторное произведение: 54.7


In [75]:
m1 = np.random.randint(0, 10, (4, 4))
m2 = np.random.randint(0, 10, (4, 4))

m1[m1 == m2]

array([0, 9])

In [78]:
A = np.array([[2, -4, 1],
              [1, -5, 3],
              [1, -1, 1]])

B = np.array([3, -1, 1])

invA = np.linalg.inv(A)
X = np.dot(invA, B)
X

array([ 2.,  0., -1.])

### Датагенератор

In [83]:
class DataGen:
    def __init__(self, data, batch, trim=True):
        self.batch = batch
        if trim:
            self.data = data[:len(data)//batch*batch]
        else:
            self.data = data
        self.len = len(self.data)
        self.cnt = 0
            
    def get_next_batch(self):
        self.cnt += self.batch
        return self.data[self.cnt - self.batch: self.cnt]
    
    def __iter__(self):
        i = 0
        while i < self.len - self.batch:
            yield self.data[i:i+self.batch]
            i += self.batch
        yield self.data[i:]
    
    def __next__(self):
        if self.cnt < self.len:
            self.cnt += self.batch
            return self.data[self.cnt - self.batch: self.cnt]
        else:
            raise StopIteration
            

data = np.array([3,24,76,34,2,6,78,9,8,456,34,53,4,32,56,54,32,5,4,8,89,4,4,6,38,234,34,3,0])

data_gen = DataGen(data, 3, False)
for i in data_gen:
    print(i)

[ 3 24 76]
[34  2  6]
[78  9  8]
[456  34  53]
[ 4 32 56]
[54 32  5]
[ 4  8 89]
[4 4 6]
[ 38 234  34]
[3 0]
